---
routes_init:
  r1:
    - dest: "10.4.4.0/24"
      next_hop: "172.31.12.2"
  r2:
    - dest: "10.1.1.0/24"
      next_hop: "172.31.12.3"
    - dest: "10.4.4.0/24"
      next_hop: "172.31.23.2"
  r3:
    - dest: "10.1.1.0/24"
      next_hop: "172.31.23.3"
    - dest: "10.4.4.0/24"
      next_hop: "172.31.34.2"
  r4:
    - dest: "10.1.1.0/24"
      next_hop: "172.31.34.2"

routes_change:
  r1:
    - dest: "10.4.99.0/24"
      next_hop: "172.31.12.2"
  r2:
    - dest: "10.4.99.0/24"
      next_hop: "172.31.23.2"
  r3:
    - dest: "10.4.99.0/24"
      next_hop: "172.31.34.2"
  r4: []
